### ISSUE TITLE
Syntax reader link with the main data

### ISSUE THREAD

**Issue by ykyyky001** [TOBgit/MaterialPlot#11]
need help with:
1. calling the property names from the data into the syntax reader, and compare the input string (property/propNode/propertyNode) with the list, if not in the list, give back an error message
2. calling the mean value column in the 'interpreter' to put it into the mean value interpreter. Now all string/property name are assign a value of 1.

**Comment by TienanLi** [comment]
To make it understandable, " the mean value column" means the "xx_mean" columns in the test csv. 

I think ky is trying to add a visit_PropNode() func in his meanInterpreter(), which can get_val from model.data. Basically the so-call meanInterpreter will finally do this:

if users input: Density^5
we should get a list as data["density_mean"] ** 5

**Comment by TienanLi** [comment]
I'll TAL at this tmr if genyez don't have time. It's kind of blocking now.

**Comment by ykyyky001** [comment]
How the function works in general:
-window popup
-user inputs an equation with texts as one of the axes, e.g. Modulus*strength/density^2
-it calculates a new column from existing Modulus, strength, and density columns, with the equation the syntax reader translated. Here if the user input a column that doesn't exit, give an error
-plot a new plot with the new axis

**Comment by TienanLi** [comment]
nice work!
