### ISSUE TITLE
Features: add selection line

### ISSUE THREAD

**Issue by ykyyky001** [TOBgit/MaterialPlot#16]
We used to have this function in the linear case. Now we will limit this function to ONLY LOG SCALE, because there’s very little physical meaning if this line is plotted in linear scale.

The plan is as follow:
1. User click on Manage Selection Line button
2. Pop up window has a list of all lines, similar to what Guaishow did for the materials pop up.
3. There you can add and delete lines by adding two sets of x and y values, i.e. defining two points on the plot
4. (For the future, or for now if it’s easy to achieve )  User can also input line thickness and color
5. Generate a straight line connecting the two points, and extend to the entire figure, after the user confirm the new inputs
6. Selection lines should be able to hide, but not delete—the info the user input for the lines need to stay there even if the line is not showing, because the info of the lines are not in the .csv file

**Comment by genyez** [comment]
data already in config.selection_lines, please do the graphic job~

**Comment by genyez** [comment]
![83f2b51f4cbd5687e9622e67cd90ee3](https://user-images.githubusercontent.com/13222726/195298619-213b6bb6-3ec4-44b3-a389-2f99e9f77cbb.png)
ui like this

**Comment by genyez** [comment]
[Delete Selection] will delete last line, for now. will make it possible to delete by context menu(right-click-menu)

**Comment by ykyyky001** [comment]
Thanks she and wanghong
