### ISSUE TITLE
Pop-up error window

### ISSUE THREAD

**Issue by ykyyky001** [TOBgit/MaterialPlot#25]
User feedback that when the labels do not exist in the CVS, they try to plot, nothing happened, but no hint.
Also the default axes (modulus, strength) is already fill in. They have a very high tendency to just try it out.
We can either add an error popup window, or remove the default axes texts there.

**Comment by genyez** [comment]
done，will popup in two circumstances: wrong syntax and missing feature

**Comment by genyez** [comment]
To make things perfect, we need to have a config file saved, to remember user's last input axis string
