### ISSUE TITLE
Feature：Family Hull

### ISSUE THREAD

**Issue by genyez** [TOBgit/MaterialPlot#3]
plot multiple hull by family field on the graph，depends on

**Comment by genyez** [comment]
Partially fulfilled by 9bfe83c
Need to chat with the product about the actually needed interaction.

**Comment by ykyyky001** [comment]
updated UI
now the user selects string columns as the category to group into family, from the dropdown list on top of the treeList. Then the user will press Refresh List, which updates the list. When the user is happy, they press generate materials bubble and generate family bubble to refresh the plot
