### ISSUE TITLE
Feature：Group Filtering

### ISSUE THREAD

**Issue by genyez** [TOBgit/MaterialPlot#4]
Filter data by UI specified group

**Comment by ykyyky001** [comment]
the items and family in the tree view can not be unselected. Could the selection be implemented?

**Comment by genyez** [comment]
a bug, let me find who broke it and kick his ass, i swear i will

**Comment by genyez** [comment]
oh my fault, fix it right the way

**Comment by genyez** [comment]
fixed， using eye icon
