### ISSUE TITLE
Feature: Support different params as the x and y axis.

### ISSUE THREAD

**Issue by genyez** [TOBgit/MaterialPlot#7]
AI 1. adjust MatItem class to make it compatible with recording more original information
AI 2. modify transformer API to make it consume needed column

**Comment by genyez** [comment]
AI1 done in c05d65c

**Comment by TienanLi** [comment]
AI 2 partially fullied by [78ab8d4](https://github.com/TOBgit/MaterialPlot/commit/78ab8d49ed36c04afb787757b10d78b5d6c19c79)

Remaining TODOs:
1) setAxesPopUp.passInfo() return latex str @ykyyky001 
2) GraphicTransformer.convertMatToSimpleEllipse() handle w and h definition @ykyyky001 @TienanLi 
3) MaterialItem.get() handle latex str interpretation and calculation @genyez @ykyyky001 @TienanLi -> related to issue#11

**Comment by TienanLi** [comment]
It seems we are all set on this. Nice job guys!
